
FROM golang:1.18-alpine as builder

ENV GO111MODULE=on \
    GOPRIVATE=github.com/sisu-network/*

WORKDIR /tmp/go-app

RUN --mount=type=secret,id=gh_token GH_TOKEN="$(cat /run/secrets/gh_token)" \
    && apk add --no-cache make gcc musl-dev linux-headers git \
    && apk add openssh \
    && git config --global url."https://${GH_TOKEN}:x-oauth-basic@github.com".insteadOf "https://github.com"

COPY go.mod .

COPY go.sum .

RUN go mod download

COPY . .

RUN go build -o ./out/deyes main.go

# Start fresh from a smaller image
FROM alpine:3.9

WORKDIR /app

COPY --from=builder /tmp/go-app/out/deyes /app/deyes

CMD ["./deyes"]
