# node:alpine will be our base image to create this image
FROM node:16.3.0-alpine

# Set the /app directory as working directory
WORKDIR /app

# Install ganache-cli globally
RUN npm install -g ganache-cli

EXPOSE 7545

# Example of how to run the docker command:
# docker run -i -t -e port=7545 -e networkId=1 ganache-cli
CMD ["sh", "-c", "ganache-cli --accounts 10 --blockTime 3 --host 0.0.0.0 --port ${port} --defaultBalanceEther 100000 --networkId ${networkId} --mnemonic 'draft attract behave allow rib raise puzzle frost neck curtain gentle bless letter parrot hold century diet budget paper fetch hat vanish wonder maximum'"]
